#!/usr/bin/python
#-*- coding:utf-8 -*-
def main():
	a = int(raw_input('enter a:'))
	b = int(raw_input('enter b:'))
	c = int(raw_input('enter c:'))
	d = int(raw_input('enter d:'))
	e = int(raw_input('enter e:'))
	if(e == a+b-c*d):
		print('1a+b-c*d')
	if(e == a+b-c/d):
		print('a+b-c/d')
	if(e == a+b*c-d):
		print('a+b*c-d')
	if(e == a+b*c/d):
	        print('a+b*c/d')
	if(e == a+b/c-d):
        	print('a+b/c-d')
	if(e == a+b/c*d):
        	print('a+b/c*d')
	if(e == a-b+c*d):
        	print('a-b+c*d')
	if(e == a-b+c/d):
        	print('a-b+c/d')
	if(e == a-b*c+d):
       		print('a-b*c+d')
	if(e == a-b*c/d):
        	print('a-b*c/d')
	if(e == a-b/c+d):
        	print('a-b/c+d')
	if(e == a-b/c*d):
        	print('a-b/c*d')
	if(e == a*b+c-d):
        	print('a*b+c-d')
	if(e == a*b+c/d):
        	print('a*b+c/d')
	if(e == a*b-c+d):
        	print('a*b-c+d')
	if(e == a*b-c/d):
        	print('a*b-c/d')
	if(e == a*b/c+d):
        	print('a*b/c+d')
	if(e == a*b/c-d):
        	print('a*b/c-d')
	if(e == a/b+c-d):
        	print('a/b+c-d')
	if(e == a/b+c*d):
        	print('a/b+c*d')
	if(e == a/b-c+d):
        	print('a/b-c+d')
	if(e == a/b-c*d):
        	print('a/b-c*d')
	if(e == a/b*c+d):
        	print('a/b*c+d')
	if(e == a/b*c/d):
        	print('a/b*c/d')
if __name__=="__main__":
	main()
